#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vim='nvim'

alias ls='ls --color=auto'
alias ll='ls --color=auto -lh'
alias la='ls --color=auto -lah'
alias lll='ls --color=auto -lah | less'

export GREP_COLOR=31
alias grep='grep --color'
